### ISSUE TITLE
ios support 

### ISSUE THREAD

**Issue by username14415** [chocoford/ExcalidrawZ#20]
Any plans for ios/mobile?
Is there any documentation? Could you explain how it works? Is it just your own implementation of whiteboard written in swift compatible (import/export) with excalidraw web app? or it's a something like JS app wrapper?

**Comment by dalisoft** [comment]
+1

**Comment by dalisoft** [comment]
iPad support would be great too

**Comment by chocoford** [comment]
@username14415 @dalisoft Thank you for your suggestion.
Originally, I had plans for this, but it wasn’t a high priority, so I didn’t put it on the agenda. The reason is that I’m still unsure whether the experience of using Excalidraw on mobile is good and whether there’s a genuine need for a canvas tool on mobile.

However, this need has been mentioned many times, I will gradually start the development of this feature, relying on iCloud to enable data synchronization across different devices.

**Comment by chocoford** [comment]
Hello everyone, I would be happy to say that:
iOS and iPadOS is currently supported. You can find it in App Store.🥳
